#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This file is part of HUBAngl.
# HUBAngl Uses Broadcaster Angle
#
# HUBAngl is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# HUBAngl is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with HUBAngl.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright (c) 2016-2017 David Testé

import gi
gi.require_version("Gst", "1.0")  # NOQA
gi.require_version('Gtk', '3.0')  # NOQA
from gi.repository import Gst
from gi.repository import Gtk

import user_interface.main_window


if __name__ == "__main__":
    Gst.init(None)
    user_interface.main_window.MainWindow()
    Gtk.main()
